version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: energydb
      DB_USER: energy
      DB_PASS: energy
      JWT_SECRET: please_change_me
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: npm run start
volumes:
  db_data:



